build:
    environment:
        python: 2.7.7
        mysql: false
        postgresql: false
        redis: false
        elasticsearch: false
        rabbitmq: false
        mongodb: false
        neo4j: false
        memcached: false
    dependencies:
        before:
            - pip install -r requirements.txt
    tests:
        override:
            - chmod +x tcpstat.py && chmod +x tests.py && sudo PATH=$PATH python ./tests.py

checks:
    python:
        code_rating: true
        duplicate_code: true
        format_bad_indentation:
            indentation: '4 spaces'
        format_mixed_indentation: true
        format_line_too_long:
            max_length: '79'
        imports_relative_import: true
        imports_wildcard_import: true
        format_bad_whitespace: true
        format_multiple_statements: true
        basic_invalid_name:
            functions: '[a-z_][a-z0-9_]{2,30}$'
            variables: '[a-z_][a-z0-9_]{2,30}$'
            whitelisted_names: 'i,j,k,ex,Run,_'
            constants: '(([A-Z_][A-Z0-9_]*)|(__.*__))$'
            attributes: '[a-z_][a-z0-9_]{2,30}$'
            arguments: '[a-z_][a-z0-9_]{2,30}$'
            class_attributes: '([A-Za-z_][A-Za-z0-9_]{2,30}|(__.*__))$'
            inline_vars: '[A-Za-z_][A-Za-z0-9_]*$'
            classes: '[A-Z_][a-zA-Z0-9]+$'
            modules: '(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+))$'
            methods: '[a-z_][a-z0-9_]{2,30}$'
        classes_no_self_argument: true
        classes_bad_mcs_method_argument: true
        classes_bad_classmethod_argument: true

filter:
    excluded_paths:
        - './tests.py'
